### ISSUE TITLE
use self.img_original to crop instead of self.img_with_detections

### ISSUE THREAD

**Issue by toedtli** [RenatoBMLR/Facial_Keypoints_Detection#1]
Thanks for the code!
In the detection method of the  FaceDetection class you might want to crop out faces on the original image instead of img_with_detections:

    def detection(self):
        faces_crop = []
        for (x, y, w, h) in self.faces:  
            obj = self.img_original[y:y + h, x:x + w]
            faces_crop.append(obj)
            cv2.rectangle(self.img_with_detections, (x, y), (x+w, y+h), (0, 255, 0), 2)
            
        return faces_crop

Otherwise in the case of overlapping boxes, you get cropped images containing lines from other detection boxes.

**Comment by RenatoBMLR** [comment]
Hi @toedtli,

Thanks for your review, you're completely right ;)
